### ISSUE TITLE
How to use with raspberry pico

### ISSUE THREAD

**Issue by allegfede** [avsg8/MLX90640_micropython#1]
Hello. Trying your code with a raspberry pi pico and the micropyrhon environment, but got a lot of problems trying to load all the library tree on the device (I use thonny).
Is there a way to integrate the lib in a single file to copy paste it in the editor?
Thanks.

**Comment by avsg8** [comment]
Sorry about the late reply. I don't check this space often. This is not a live project and I don't have plans to try it out on pico in the short term. Sorry I couldn't be of more help.
